// Code generated by abstraction-idl from abstraction-credentials/credentials.thrift. DO NOT EDIT.

// abstraction.credentials.api: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

/** Enforcer-only application of a named credential to one request. The receiving host designates the consuming services by program, as rights DecideFor designates enforcers; nil designation refuses every call. Headers cross this boundary to a designated service only, never to an application client, and never to a remote host. A remote provider holds its own applier and registrations; delegation carries the name. On platforms without process and path proof every Apply is forbidden. */
export declare class ApplierClient {
  constructor(transport: FrameTransport);
  /** Evaluate whether Apply would succeed for this use, for admission and adopter preflight. Same designation and policy as Apply; reads no secret; appends a checked or refused audit entry. */
  check(usage: Use): Promise<CheckResult>;
  /** Read the secret for one outgoing request. Only an explicitly designated enforcer program, bound by native Program proof, is accepted; same-account access alone is forbidden. The holder rechecks rights on every call and never caches a decision or a value across calls. */
  apply(usage: Use): Promise<ApplyResult>;
}

export declare const ApplierService: Readonly<{ wireName: "abstraction.credentials/applier@1"; Client: typeof ApplierClient }>;

export type ApplyOutcome = (typeof ApplyOutcome)[keyof typeof ApplyOutcome];
export declare const ApplyOutcome: Readonly<{ Applied: "applied"; Unknown: "unknown"; Expired: "expired"; Revoked: "revoked"; Lost: "lost"; NotPermitted: "not_permitted"; TargetRefused: "target_refused"; ConsumerRefused: "consumer_refused"; UnsupportedKind: "unsupported_kind"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// headers is present exactly for applied and holds the request headers for this
// one request: Authorization for bearer and challenge kinds, the registered
// header name for kind header. The consuming service sends them once, keeps
// them out of every record, log and reply, and calls Apply again for the next
// request, redirect or resumed range. Other outcomes carry no headers.
// not_permitted means the rights decision for subject,
// abstraction.credentials/apply and credential:<name> was anything except
// permitted; the exact word is in the audit trail. target_refused and
// consumer_refused name Scope mismatches. forbidden means the calling peer is
// not a designated enforcer, or the subject could not be bound on this
// platform. unavailable means the rights service or the platform store could
// not be reached; nothing was applied.
export interface ApplyResult {
  outcome: ApplyOutcome;
  revision: string;
  headers: { [key: string]: string };
}

// One retained event in journal order. event is an open word: stored, rotated,
// revoked, expired, lost, retired, checked, applied, refused. subject is the
// asserted submitting or registering subject; consumer and target are present
// for checked, applied and refused; outcome is the exact holder or rights
// outcome word. Entries carry names and never values.
export interface AuditEntry {
  sequence: bigint;
  time: string;
  event: string;
  name: string;
  revision: string;
  subject: Subject | null;
  consumer: string;
  target: string;
  outcome: string;
}

// page carries at most max_entries entries after the cursor. The journal
// retains Limits.audit_capacity entries for Limits.audit_retention_ms per
// account; a cursor older than the retained journal, or from another provider
// epoch, returns gap. Refusals carry no entries, an unchanged cursor and
// at_end=false.
export interface AuditPage {
  outcome: PageOutcome;
  entries: AuditEntry[];
  next: string;
  atEnd: boolean;
}

// applied means Apply with the same Use would carry headers now. revision is
// present for evaluated records. No secret is read for a check.
export interface CheckResult {
  outcome: ApplyOutcome;
  revision: string;
}

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

/** Register, rotate, revoke and inspect credentials by name in the receiving account. Same-account identity alone grants nothing; each call is a rights decision on the bound receiving subject. No call returns secret bytes, and metadata derives nothing from them. An absent policy service reads unavailable. An unconfigured platform store or a machine-scope runtime reads no_secure_store; the provider substitutes no environment, file or configuration source. */
export declare class HolderClient {
  constructor(transport: FrameTransport);
  /** Conditionally register one secret for the receiving account. Gated by abstraction.credentials/holder.manage on resource account for the bound receiving subject; authorization precedes every store effect. The secret leaves the request only into the configured platform store. Returns stored, conflict, invalid, unsupported_kind, no_secure_store, exhausted, forbidden or unavailable. */
  store(expectedRevision: string, registration: Registration): Promise<StoreResult>;
  /** Conditionally replace the bytes of an existing record and its expiry; kind and scope are unchanged. Gated by holder.manage. */
  rotate(expectedRevision: string, rotation: Rotation): Promise<RotateResult>;
  /** Conditionally destroy the bytes and tombstone the record. Gated by holder.manage. A failed or uncertain reply claims no destruction; inspect List before another intent. */
  revoke(expectedRevision: string, name: string): Promise<RevokeResult>;
  /** Read the receiving account's records and the provider limits. Gated by abstraction.credentials/holder.read on resource account; every continuation rechecks. limit is 1..64. */
  list(cursor: string, limit: bigint): Promise<MetadataPage>;
  /** Read the receiving account's retained credential events. Gated by holder.read. Empty cursor starts at the oldest retained entry; max_entries is 1..256. */
  audit(cursor: string, maxEntries: bigint): Promise<AuditPage>;
}

export declare const HolderService: Readonly<{ wireName: "abstraction.credentials/holder@1"; Client: typeof HolderClient }>;

// Provider-declared bounds, read through List. max_secret_bytes is at most 4096
// and is lower where the configured store bounds it. secure_store names the
// configured store: SecureStore names this version's standard backends,
// provider extensions are retained, and refusal-page zero limits carry the
// empty word. supported_kinds are the kinds an applier on this runtime can
// apply; Store refuses any other.
export interface Limits {
  maxCredentials: bigint;
  maxSecretBytes: bigint;
  tombstoneRetentionMs: bigint;
  auditRetentionMs: bigint;
  auditCapacity: bigint;
  secureStore: SecureStore | (string & {});
  supportedKinds: string[];
}

// Metadata only. registered_by is the subject the receiving boundary bound from
// native Program proof when the record was stored, asserted by the holder; it
// is provenance and carries no proof. No field derives from the secret bytes:
// no length, hash, prefix or suffix. header is present exactly for kind header.
export interface Metadata {
  name: string;
  kind: string;
  revision: string;
  state: State | (string & {});
  scope: Scope;
  registeredBy: Subject;
  registered: string;
  expires: string;
  header: string;
  lastApplied: string;
}

// page carries 0..limit records of the receiving account in name order,
// including tombstones inside retention. Cursors are at most 256 bytes, bind
// receiving account and provider epoch, and return gap after restart or scope
// mismatch; restart from an empty cursor. A noncomplete page has a nonempty
// next. Refusals carry zero limits, no records, empty next and complete=false.
export interface MetadataPage {
  outcome: PageOutcome;
  limits: Limits;
  records: Metadata[];
  next: string;
  complete: boolean;
}

export type PageOutcome = (typeof PageOutcome)[keyof typeof PageOutcome];
export declare const PageOutcome: Readonly<{ Page: "page"; Gap: "gap"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "bad_timestamp" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_binary" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// name is 1..64 bytes of A-Z a-z 0-9 _ - . and unique within the receiving
// account. kind is a seed or <owner>/<name>@<n>. secret is
// 1..Limits.max_secret_bytes bytes with no control character other than tab,
// and is written only to the configured platform store; this document is never
// retained, logged or echoed. header is an HTTP field name, required for kind
// header and refused otherwise. expires, when present, is after the receiving
// clock.
export interface Registration {
  name: string;
  kind: string;
  scope: Scope;
  expires: string;
  header: string;
  secret: Uint8Array;
}

export type RevokeOutcome = (typeof RevokeOutcome)[keyof typeof RevokeOutcome];
export declare const RevokeOutcome: Readonly<{ Revoked: "revoked"; Unknown: "unknown"; Conflict: "conflict"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// revoked destroys the bytes at once and keeps a tombstone for
// Limits.tombstone_retention_ms, during which Apply reads revoked; afterwards
// the name reads unknown and may be registered again. conflict carries the
// current revision. invalid is a malformed name or revision. A platform store
// that cannot destroy the bytes reads unavailable and the record is unchanged.
export interface RevokeResult {
  outcome: RevokeOutcome;
  revision: string;
}

export type RotateOutcome = (typeof RotateOutcome)[keyof typeof RotateOutcome];
export declare const RotateOutcome: Readonly<{ Rotated: "rotated"; Unknown: "unknown"; Conflict: "conflict"; Invalid: "invalid"; NoSecureStore: "no_secure_store"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// rotated carries the new revision; the previous bytes are destroyed once the
// new item is written, and an in-flight Apply uses the new bytes on its next
// request. A lost or expired record returns to active. conflict carries current
// metadata. A revoked record reads unknown.
export interface RotateResult {
  outcome: RotateOutcome;
  revision: string;
  current: Metadata | null;
}

// Replacement bytes and expiry for an existing record. secret follows
// Registration.secret and is never retained, logged or echoed. Absent expires
// clears expiry; a present expires is after the receiving clock.
export interface Rotation {
  name: string;
  expires: string;
  secret: Uint8Array;
}

// targets: 1..16 lowercase host names, each covering itself and its subdomains;
// no scheme, port, path or wildcard characters. consumers: 1..8 wire contract
// names of services that may apply the credential. Both lists are exact; a host
// or contract outside them is refused at Apply.
export interface Scope {
  targets: string[];
  consumers: string[];
}

export type SecureStore = (typeof SecureStore)[keyof typeof SecureStore];
export declare const SecureStore: Readonly<{ WindowsCredentialManager: "windows-credential-manager"; SecretService: "secret-service"; File0600: "file-0600"; MacosKeychain: "macos-keychain"; None: "none" }>;

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode" }>;

export type State = (typeof State)[keyof typeof State];
export declare const State: Readonly<{ Active: "active"; Expired: "expired"; Revoked: "revoked"; Lost: "lost" }>;

export type StoreOutcome = (typeof StoreOutcome)[keyof typeof StoreOutcome];
export declare const StoreOutcome: Readonly<{ Stored: "stored"; Conflict: "conflict"; Invalid: "invalid"; UnsupportedKind: "unsupported_kind"; NoSecureStore: "no_secure_store"; Exhausted: "exhausted"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// stored carries the new revision and current metadata. conflict carries the
// revision and current metadata observed inside the conditional edit. Other
// outcomes carry an empty revision and no current. An empty expected revision
// requires that the name not exist; a tombstoned name conflicts until retention
// elapses. A stale expected revision conflicts even when the desired state
// already holds. A lost reply is uncertain: reconcile from current or List
// before another edit. no_secure_store means this runtime has no configured
// platform store, or is a machine-scope runtime; nothing was retained anywhere.
// exhausted means the account holds its maximum number of records.
export interface StoreResult {
  outcome: StoreOutcome;
  revision: string;
  current: Metadata | null;
}

// Account identifier and normalized absolute executable path, the same shape as
// abstraction.rights Subject. It is an assertion by the party that bound native
// Program proof: the holder for registered_by and audit entries of holder
// calls, the designated enforcer for Use.subject. It contains no proof.
export interface Subject {
  account: string;
  program: string;
}

// subject is the submitting caller as bound at the consuming service's own
// boundary and asserted by that authorized enforcer; serialization conveys no
// proof. consumer is the calling service's wire contract name: a consumers seed
// or <owner>/<name>@<n>. target is the lowercase host the request will open.
// challenge carries kind-specific input, for example a registry authenticate
// challenge, and is refused as invalid for the seed kinds.
export interface Use {
  subject: Subject;
  consumer: string;
  name: string;
  target: string;
  challenge: string;
}

export declare const consumers: readonly ["abstraction.download/http-execution@1", "abstraction.model/resolver@1", "abstraction.inference/chat@1"];

export declare const credentialKinds: readonly ["bearer", "header"];

export declare function decode(data: Uint8Array): Registration;

export declare function encode(v: Registration): Uint8Array;

export declare const executionGuarantees: readonly ["abstraction.download/credentials@1"];

export declare function newApplyResult(): ApplyResult;

export declare function newAuditEntry(): AuditEntry;

export declare function newAuditPage(): AuditPage;

export declare function newCheckResult(): CheckResult;

export declare function newLimits(): Limits;

export declare function newMetadata(): Metadata;

export declare function newMetadataPage(): MetadataPage;

export declare function newRegistration(): Registration;

export declare function newRevokeResult(): RevokeResult;

export declare function newRotateResult(): RotateResult;

export declare function newRotation(): Rotation;

export declare function newScope(): Scope;

export declare function newStoreResult(): StoreResult;

export declare function newSubject(): Subject;

export declare function newUse(): Use;

export declare const resourceActions: readonly ["abstraction.credentials/holder.manage", "abstraction.credentials/holder.read", "abstraction.credentials/apply"];

export {};
